require('dotenv').config();
const basePath = process.cwd();
const fs = require("fs");
const { MODE } = require(`${basePath}/constants/blend_mode.js`);
const { NETWORK } = require(`${basePath}/constants/network.js`);

const network = NETWORK.eth;

// General metadata for Ethereum
const namePrefix = "Unknown Federation";
const description = "A collections of cadets, officers and admirals of the Unknown Federation (abbvreviated as UF), a multi-national union of individuals who explores the vast body of space in search of new life and new civilisations. The Unknown Federation operates semi-autonomously under a united government, founded on the principles of liberty, equality, peace, justice, and progress, with the purpose of furthering the universal rights of all sentient life. Their main goals is to acquire knowledge and resources to facilitate peaceful cooperation, scientific development, space exploration, and defense."
const baseUri = "ipfs://NewUriToReplace"; // This will be replaced automatically

const layerConfigurations = [
  {
    growEditionSizeTo: 20,
    layersOrder: [
      { name: "Background" },
      { name: "Aanandi" },
      { name: "Facial Scar 2" },        
      { name: "Uniform 4" },
      { name: "Rank 1" },
      { name: "Eyebrows 2" },
      { name: "Eyes 2" },
      { name: "Nose 2" },
      { name: "Lips 2" },
      { name: "Gadgets 4" },
      { name: "Apparatus 4" },
      { name: "Hijab 2" },
    ],
  },
	{
    growEditionSizeTo: 40,
    layersOrder: [
      { name: "Background" },
      { name: "Aashvi" },
      { name: "Facial Scar 2" },        
      { name: "Uniform 2" },
      { name: "Rank 3" },
      { name: "Eyebrows 2" },
      { name: "Eyes 2" },
      { name: "Nose 2" },
      { name: "Lips 2" },
      { name: "Gadgets 3" },
      { name: "Apparatus 3" },
      { name: "Hair 2" },
    ],
  },
	{
    growEditionSizeTo: 60,
    layersOrder: [
      { name: "Background" },
      { name: "Ailani" },
      { name: "Facial Scar 5" },        
      { name: "Uniform 1" },
      { name: "Rank 2" },
      { name: "Eyebrows 5" },
      { name: "Eyes 5" },
      { name: "Nose 5" },
      { name: "Lips 5" },
      { name: "Gadgets 10" },
      { name: "Apparatus 10" },
      { name: "Hijab 5" },
    ],
  },
	{
    growEditionSizeTo: 80,
    layersOrder: [
      { name: "Background" },
      { name: "Farangis" },
      { name: "Facial Scar 4" },        
      { name: "Uniform 2" },
      { name: "Rank 3" },
      { name: "Eyebrows 4" },
      { name: "Eyes 4" },
      { name: "Nose 4" },
      { name: "Lips 4" },
      { name: "Gadgets 8" },
      { name: "Apparatus 8" },
      { name: "Hijab 4" },
    ],
  },
	{
    growEditionSizeTo: 100,
    layersOrder: [
      { name: "Background" },
      { name: "Ajith" },
      { name: "Facial Scar 7" },
      { name: "Uniform 9" },
      { name: "Rank 7" },
      { name: "Eyebrows 7" },
      { name: "Eyes 7" },
      { name: "Nose 7" },
      { name: "Lips 7" },			
      { name: "Gadgets 12" },
      { name: "Facial Features 2" },	
      { name: "Hair 7" },
    ],
  },
	{
    growEditionSizeTo: 120,
    layersOrder: [
      { name: "Background" },
      { name: "Alana" },
      { name: "Facial Scar 2" },        
      { name: "Uniform 1" },
      { name: "Rank 2" },
      { name: "Eyebrows 2" },
      { name: "Eyes 2" },
      { name: "Nose 2" },
      { name: "Lips 2" },
      { name: "Gadgets 3" },
      { name: "Apparatus 3" },
      { name: "Hair 2" },
    ],
  },
	{
    growEditionSizeTo: 140,
    layersOrder: [
      { name: "Background" },
      { name: "Alec" },
      { name: "Facial Scar 8" },        
      { name: "Uniform 9" },
      { name: "Rank 7" },
      { name: "Eyebrows 8" },
      { name: "Eyes 8" },
      { name: "Nose 8" },
      { name: "Lips 8" },				
      { name: "Gadgets 13" },
      { name: "Facial Features 3" },
      { name: "Hair 8" },
    ],
  },
	{
    growEditionSizeTo: 160,
    layersOrder: [
      { name: "Background" },
      { name: "Alemayehu" },
      { name: "Facial Scar 6" },
      { name: "Uniform 9" },
      { name: "Rank 7" },
      { name: "Eyebrows 6" },
      { name: "Eyes 6" },
      { name: "Nose 6" },
      { name: "Lips 6" },			
      { name: "Gadgets 11" },
      { name: "Facial Features 1" },	
      { name: "Hair 6" },
    ],
  },
	{
    growEditionSizeTo: 180,
    layersOrder: [
      { name: "Background" },
      { name: "Aleynah" },
      { name: "Facial Scar 5" },        
      { name: "Uniform 5" },
      { name: "Rank 4" },
      { name: "Eyebrows 5" },
      { name: "Eyes 5" },
      { name: "Nose 5" },
      { name: "Lips 5" },
      { name: "Gadgets 9" },
      { name: "Apparatus 9" },
      { name: "Hair 5" },
    ],
  },
	{
    growEditionSizeTo: 200,
    layersOrder: [
      { name: "Background" },
      { name: "Alice" },
      { name: "Facial Scar 3" },        
      { name: "Uniform 2" },
      { name: "Rank 3" },
      { name: "Eyebrows 3" },
      { name: "Eyes 3" },
      { name: "Nose 3" },
      { name: "Lips 3" },
      { name: "Gadgets 5" },
      { name: "Apparatus 5" },
      { name: "Hair 3" },
    ],
  },
	{
    growEditionSizeTo: 220,
    layersOrder: [
      { name: "Background" },
      { name: "Allina" },
      { name: "Facial Scar 5" },        
      { name: "Uniform 7" },
      { name: "Rank 4" },
      { name: "Eyebrows 5" },
      { name: "Eyes 5" },
      { name: "Nose 5" },
      { name: "Lips 5" },
      { name: "Gadgets 10" },
      { name: "Apparatus 10" },
      { name: "Hijab 5" },
    ],
  },
	{
    growEditionSizeTo: 240,
    layersOrder: [
      { name: "Background" },
      { name: "Azadeh" },
      { name: "Facial Scar 4" },
      { name: "Uniform 2" },
      { name: "Rank 3" },
      { name: "Eyebrows 4" },
      { name: "Eyes 4" },
      { name: "Nose 4" },
      { name: "Lips 4" },
      { name: "Gadgets 7" },
      { name: "Apparatus 7" },
      { name: "Hair 4" },
    ],
  },
	{
    growEditionSizeTo: 260,
    layersOrder: [
       { name: "Background" },
      { name: "Baldan" },
      { name: "Facial Scar 7" },        
      { name: "Uniform 11" },
      { name: "Rank 5" },
      { name: "Eyebrows 7" },
      { name: "Eyes 7" },
      { name: "Nose 7" },
      { name: "Lips 7" },				
      { name: "Gadgets 12" },
      { name: "Facial Features 2" },
      { name: "Hair 7" },
    ],
  },
	{
    growEditionSizeTo: 280,
    layersOrder: [
       { name: "Background" },
      { name: "Becky" },
      { name: "Facial Scar 3" },        
      { name: "Uniform 3" },
      { name: "Rank 4" },
      { name: "Eyebrows 3" },
      { name: "Eyes 3" },
      { name: "Nose 3" },
      { name: "Lips 3" },
      { name: "Gadgets 5" },
      { name: "Apparatus 5" },
      { name: "Hair 3" },
    ],
  },
	{
    growEditionSizeTo: 300,
    layersOrder: [
      { name: "Background" },
      { name: "Behati" },
      { name: "Facial Scar 1" },        
      { name: "Uniform 2" },
      { name: "Rank 3" },
      { name: "Eyebrows 1" },
      { name: "Eyes 1" },
      { name: "Nose 1" },
      { name: "Lips 1" },
      { name: "Gadgets 1" },
      { name: "Apparatus 1" },
      { name: "Hair 1" },
    ],
  },
	{
    growEditionSizeTo: 320,
    layersOrder: [
      { name: "Background" },
      { name: "Bongani" },
      { name: "Facial Scar 6" },        
      { name: "Uniform 10" },
      { name: "Rank 8" },
      { name: "Eyebrows 6" },
      { name: "Eyes 6" },
      { name: "Nose 6" },
      { name: "Lips 6" },			
      { name: "Gadgets 11" },
      { name: "Facial Features 1" },	
      { name: "Hair 6" },
    ],
  },
	{
    growEditionSizeTo: 340,
    layersOrder: [
      { name: "Background" },
      { name: "Chao Xing" },
      { name: "Facial Scar 2" },        
      { name: "Uniform 3" },
      { name: "Rank 4" },
      { name: "Eyebrows 2" },
      { name: "Eyes 2" },
      { name: "Nose 2" },
      { name: "Lips 2" },
      { name: "Gadgets 4" },
      { name: "Apparatus 4" },
      { name: "Hijab 2" },
    ],
  },
	{
    growEditionSizeTo: 360,
    layersOrder: [
      { name: "Background" },
      { name: "Chathura" },
      { name: "Facial Scar 7" },        
      { name: "Uniform 10" },
      { name: "Rank 8" },
      { name: "Eyebrows 7" },
      { name: "Eyes 7" },
      { name: "Nose 7" },
      { name: "Lips 7" },			
      { name: "Gadgets 12" },
      { name: "Facial Features 2" },	
      { name: "Hair 7" },
    ],
  },
	{
    growEditionSizeTo: 380,
    layersOrder: [
      { name: "Background" },
      { name: "Chinasa" },
      { name: "Facial Scar 6" },        
      { name: "Uniform 11" },
      { name: "Rank 5" },
      { name: "Eyebrows 6" },
      { name: "Eyes 6" },
      { name: "Nose 6" },
      { name: "Lips 6" },				
      { name: "Gadgets 11" },
      { name: "Facial Features 1" },
      { name: "Hair 6" },
    ],
  },
	{
    growEditionSizeTo: 400,
    layersOrder: [
      { name: "Background" },
      { name: "Damian" },
      { name: "Facial Scar 8" },        
      { name: "Uniform 10" },
      { name: "Rank 8" },
      { name: "Eyebrows 8" },
      { name: "Eyes 8" },
      { name: "Nose 8" },
      { name: "Lips 8" },			
      { name: "Gadgets 13" },
      { name: "Facial Features 3" },	
      { name: "Hair 8" },
    ],
  },
	{
    growEditionSizeTo: 420,
    layersOrder: [
      { name: "Background" },
      { name: "Taher" },
      { name: "Facial Scar 9" },        
      { name: "Uniform 11" },
      { name: "Rank 5" },
      { name: "Eyebrows 9" },
      { name: "Eyes 9" },
      { name: "Nose 9" },
      { name: "Lips 9" },				
      { name: "Gadgets 14" },
      { name: "Facial Features 4" },
      { name: "Hair 9" },
    ],
  },
	{
    growEditionSizeTo: 440,
    layersOrder: [
      { name: "Background" },
      { name: "Ebele" },
      { name: "Facial Scar 1" },         
      { name: "Uniform 7" },
      { name: "Rank 4" },
      { name: "Eyebrows 1" },
      { name: "Eyes 1" },
      { name: "Nose 1" },
      { name: "Lips 1" },
      { name: "Gadgets 2" },
      { name: "Apparatus 2" },
      { name: "Hijab 1" },
    ],
  },
	{
    growEditionSizeTo: 460,
    layersOrder: [
      { name: "Background" },
      { name: "Ehuang" },
      { name: "Facial Scar 2" },        
      { name: "Uniform 5" },
      { name: "Rank 4" },
      { name: "Eyebrows 2" },
      { name: "Eyes 2" },
      { name: "Nose 2" },
      { name: "Lips 2" },
      { name: "Gadgets 4" },
      { name: "Apparatus 4" },
      { name: "Hijab 2" },
    ],
  },
	{
    growEditionSizeTo: 480,
    layersOrder: [
      { name: "Background" },
      { name: "Emily" },
      { name: "Facial Scar 3" },        
      { name: "Uniform 7" },
      { name: "Rank 4" },
      { name: "Eyebrows 3" },
      { name: "Eyes 3" },
      { name: "Nose 3" },
      { name: "Lips 3" },
      { name: "Gadgets 5" },
      { name: "Apparatus 5" },
      { name: "Hair 3" },
    ],
  },
	{
    growEditionSizeTo: 500,
    layersOrder: [
      { name: "Background" },
      { name: "Fayola" },
      { name: "Facial Scar 1" },         
      { name: "Uniform 6" },
      { name: "Rank 4" },
      { name: "Eyebrows 1" },
      { name: "Eyes 1" },
      { name: "Nose 1" },
      { name: "Lips 1" },
      { name: "Gadgets 2" },
      { name: "Apparatus 2" },
      { name: "Hijab 1" },
    ],
  },
	{
    growEditionSizeTo: 520,
    layersOrder: [
      { name: "Background" },
      { name: "Fereshteh" },
      { name: "Facial Scar 4" },        
      { name: "Uniform 5" },
      { name: "Rank 4" },
      { name: "Eyebrows 4" },
      { name: "Eyes 4" },
      { name: "Nose 4" },
      { name: "Lips 4" },
      { name: "Gadgets 7" },
      { name: "Apparatus 7" },
      { name: "Hair 4" },
    ],
  },
	{
    growEditionSizeTo: 540,
    layersOrder: [
      { name: "Background" },
      { name: "Gabby" },
      { name: "Facial Scar 3" },        
      { name: "Uniform 4" },
      { name: "Rank 1" },
      { name: "Eyebrows 3" },
      { name: "Eyes 3" },
      { name: "Nose 3" },
      { name: "Lips 3" },
      { name: "Gadgets 5" },
      { name: "Apparatus 5" },
      { name: "Hair 3" },
    ],
  },
	{
    growEditionSizeTo: 560,
    layersOrder: [
      { name: "Background" },
      { name: "Gala" },
      { name: "Facial Scar 2" },        
      { name: "Uniform 2" },
      { name: "Rank 3" },
      { name: "Eyebrows 2" },
      { name: "Eyes 2" },
      { name: "Nose 2" },
      { name: "Lips 2" },
      { name: "Gadgets 4" },
      { name: "Apparatus 4" },
      { name: "Hijab 2" },
    ],
  },
	{
    growEditionSizeTo: 580,
    layersOrder: [
      { name: "Background" },
      { name: "Gunnar" },
      { name: "Facial Scar 8" },        
      { name: "Uniform 14" },
      { name: "Rank 8" },
      { name: "Eyebrows 8" },
      { name: "Eyes 8" },
      { name: "Nose 8" },
      { name: "Lips 8" },				
      { name: "Gadgets 13" },
      { name: "Facial Features 3" },
      { name: "Hair 8" },
    ],
  },
	{
    growEditionSizeTo: 600,
    layersOrder: [
      { name: "Background" },
      { name: "Hakim" },
      { name: "Facial Scar 6" },        
      { name: "Uniform 14" },
      { name: "Rank 8" },
      { name: "Eyebrows 6" },
      { name: "Eyes 6" },
      { name: "Nose 6" },
      { name: "Lips 6" },			
      { name: "Gadgets 11" },
      { name: "Facial Features 1" },	
      { name: "Hair 6" },
    ],
  },
	{
    growEditionSizeTo: 620,
    layersOrder: [
      { name: "Background" },
      { name: "Hana" },
      { name: "Facial Scar 2" },        
      { name: "Uniform 7" },
      { name: "Rank 4" },
      { name: "Eyebrows 2" },
      { name: "Eyes 2" },
      { name: "Nose 2" },
      { name: "Lips 2" },
      { name: "Gadgets 3" },
      { name: "Apparatus 3" },
      { name: "Hair 2" },
    ],
  },
	{
    growEditionSizeTo: 640,
    layersOrder: [
      { name: "Background" },
      { name: "Hiroshi" },
      { name: "Facial Scar 7" },        
      { name: "Uniform 12" },
      { name: "Rank 8" },
      { name: "Eyebrows 7" },
      { name: "Eyes 7" },
      { name: "Nose 7" },
      { name: "Lips 7" },			
      { name: "Gadgets 12" },
      { name: "Facial Features 2" },	
      { name: "Hair 7" },
    ],
  },
	{
    growEditionSizeTo: 660,
    layersOrder: [
      { name: "Background" },
      { name: "Ife" },
      { name: "Facial Scar 1" }, 
      { name: "Uniform 2" },
      { name: "Rank 3" },
      { name: "Eyebrows 1" },
      { name: "Eyes 1" },
      { name: "Nose 1" },
      { name: "Lips 1" },
      { name: "Gadgets 2" },
      { name: "Apparatus 2" },
      { name: "Hijab 1" },
    ],
  },
	{
    growEditionSizeTo: 680,
    layersOrder: [
       { name: "Background" },
      { name: "Firouz" },
      { name: "Facial Scar 9" },
      { name: "Uniform 9" },
      { name: "Rank 7" },
      { name: "Eyebrows 9" },
      { name: "Eyes 9" },
      { name: "Nose 9" },
      { name: "Lips 9" },			
      { name: "Gadgets 14" },
      { name: "Facial Features 4" },	
      { name: "Hair 9" },
    ],
  },
	{
    growEditionSizeTo: 700,
    layersOrder: [
      { name: "Background" },
      { name: "Imamu" },
      { name: "Facial Scar 6" },        
      { name: "Uniform 12" },
      { name: "Rank 8" },
      { name: "Eyebrows 6" },
      { name: "Eyes 6" },
      { name: "Nose 6" },
      { name: "Lips 6" },				
      { name: "Gadgets 11" },
      { name: "Facial Features 1" },
      { name: "Hair 6" },
    ],
  },
	{
    growEditionSizeTo: 720,
    layersOrder: [
      { name: "Background" },
      { name: "Inoke" },
      { name: "Facial Scar 10" },        
      { name: "Uniform 10" },
      { name: "Rank 8" },
      { name: "Eyebrows 10" },
      { name: "Eyes 10" },
      { name: "Nose 10" },
      { name: "Lips 10" },				
      { name: "Gadgets 15" },
      { name: "Facial Features 5" },
      { name: "Hair 10" },
    ],
  },
	{
    growEditionSizeTo: 740,
    layersOrder: [
      { name: "Background" },
      { name: "Iona" },
      { name: "Facial Scar 2" },        
      { name: "Uniform 1" },
      { name: "Rank 2" },
      { name: "Eyebrows 2" },
      { name: "Eyes 2" },
      { name: "Nose 2" },
      { name: "Lips 2" },
      { name: "Gadgets 4" },
      { name: "Apparatus 4" },
      { name: "Hijab 2" },
    ],
  },
	{
    growEditionSizeTo: 760,
    layersOrder: [
      { name: "Background" },
      { name: "Ghasem" },
      { name: "Facial Scar 9" },        
      { name: "Uniform 12" },
      { name: "Rank 8" },
      { name: "Eyebrows 9" },
      { name: "Eyes 9" },
      { name: "Nose 9" },
      { name: "Lips 9" },			
      { name: "Gadgets 14" },
      { name: "Facial Features 4" },	
      { name: "Hair 9" },
    ],
  },
	{
    growEditionSizeTo: 780,
    layersOrder: [
      { name: "Background" },
      { name: "Jabroot" },
      { name: "Facial Scar 7" },        
      { name: "Uniform 13" },
      { name: "Rank 8" },
      { name: "Eyebrows 7" },
      { name: "Eyes 7" },
      { name: "Nose 7" },
      { name: "Lips 7" },				
      { name: "Gadgets 12" },
      { name: "Facial Features 2" },
      { name: "Hair 7" },
    ],
  },
	{
    growEditionSizeTo: 800,
    layersOrder: [
      { name: "Background" },
      { name: "Jacquelin" },
      { name: "Facial Scar 3" },        
      { name: "Uniform 7" },
      { name: "Rank 4" },
      { name: "Eyebrows 3" },
      { name: "Eyes 3" },
      { name: "Nose 3" },
      { name: "Lips 3" },
      { name: "Gadgets 6" },
      { name: "Apparatus 6" },
      { name: "Hijab 3" },
    ],
  },
	{
    growEditionSizeTo: 820,
    layersOrder: [
      { name: "Background" },
      { name: "Jane" },
      { name: "Facial Scar 3" },        
      { name: "Uniform 1" },
      { name: "Rank 2" },
      { name: "Eyebrows 3" },
      { name: "Eyes 3" },
      { name: "Nose 3" },
      { name: "Lips 3" },
      { name: "Gadgets 5" },
      { name: "Apparatus 5" },
      { name: "Hair 3" },
    ],
  },
	{
    growEditionSizeTo: 840,
    layersOrder: [
      { name: "Background" },
      { name: "Jason" },
      { name: "Facial Scar 8" },        
      { name: "Uniform 12" },
      { name: "Rank 8" },
      { name: "Eyebrows 8" },
      { name: "Eyes 8" },
      { name: "Nose 8" },
      { name: "Lips 8" },				
      { name: "Gadgets 13" },
      { name: "Facial Features 3" },
      { name: "Hair 8" },
    ],
  },
	{
    growEditionSizeTo: 860,
    layersOrder: [
      { name: "Background" },
      { name: "Josephine" },
      { name: "Facial Scar 3" },        
      { name: "Uniform 6" },
      { name: "Rank 4" },
      { name: "Eyebrows 3" },
      { name: "Eyes 3" },
      { name: "Nose 3" },
      { name: "Lips 3" },
      { name: "Gadgets 5" },
      { name: "Apparatus 5" },
      { name: "Hair 3" },
    ],
  },
	{
    growEditionSizeTo: 880,
    layersOrder: [
      { name: "Background" },
      { name: "Kamali" },
      { name: "Facial Scar 1" },         
      { name: "Uniform 1" },
      { name: "Rank 2" },
      { name: "Eyebrows 1" },
      { name: "Eyes 1" },
      { name: "Nose 1" },
      { name: "Lips 1" },
      { name: "Gadgets 2" },
      { name: "Apparatus 2" },
      { name: "Hijab 1" },
    ],
  },
	{
    growEditionSizeTo: 900,
    layersOrder: [
      { name: "Background" },
      { name: "Kanoa" },
      { name: "Facial Scar 10" },        
      { name: "Uniform 11" },
      { name: "Rank 5" },
      { name: "Eyebrows 10" },
      { name: "Eyes 10" },
      { name: "Nose 10" },
      { name: "Lips 10" },				
      { name: "Gadgets 15" },
      { name: "Facial Features 5" },
      { name: "Hair 10" },
    ],
  },
	{
    growEditionSizeTo: 920,
    layersOrder: [
      { name: "Background" },
      { name: "Kapena" },
      { name: "Facial Scar 5" },        
      { name: "Uniform 2" },
      { name: "Rank 3" },
      { name: "Eyebrows 5" },
      { name: "Eyes 5" },
      { name: "Nose 5" },
      { name: "Lips 5" },
      { name: "Gadgets 10" },
      { name: "Apparatus 10" },
      { name: "Hijab 5" },
    ],
  },
	{
    growEditionSizeTo: 940,
    layersOrder: [
      { name: "Background" },
      { name: "Kasigo" },
      { name: "Facial Scar 6" },        
      { name: "Uniform 8" },
      { name: "Rank 6" },
      { name: "Eyebrows 6" },
      { name: "Eyes 6" },
      { name: "Nose 6" },
      { name: "Lips 6" },			
      { name: "Gadgets 11" },
      { name: "Facial Features 1" },	
      { name: "Hair 6" },
    ],
  },
	{
    growEditionSizeTo: 960,
    layersOrder: [
      { name: "Background" },
      { name: "Kealii" },
      { name: "Facial Scar 5" },        
      { name: "Uniform 1" },
      { name: "Rank 2" },
      { name: "Eyebrows 5" },
      { name: "Eyes 5" },
      { name: "Nose 5" },
      { name: "Lips 5" },
      { name: "Gadgets 9" },
      { name: "Apparatus 9" },
      { name: "Hair 5" },
    ],
  },
	{
    growEditionSizeTo: 980,
    layersOrder: [
      { name: "Background" },
      { name: "Keikiokalani" },
      { name: "Facial Scar 5" },        
      { name: "Uniform 3" },
      { name: "Rank 4" },
      { name: "Eyebrows 5" },
      { name: "Eyes 5" },
      { name: "Nose 5" },
      { name: "Lips 5" },
      { name: "Gadgets 10" },
      { name: "Apparatus 10" },
      { name: "Hijab 5" },
    ],
  },
	{
    growEditionSizeTo: 1000,
    layersOrder: [
      { name: "Background" },
      { name: "Khadijeh" },
      { name: "Facial Scar 4" },        
      { name: "Uniform 1" },
      { name: "Rank 2" },
      { name: "Eyebrows 4" },
      { name: "Eyes 4" },
      { name: "Nose 4" },
      { name: "Lips 4" },
      { name: "Gadgets 8" },
      { name: "Apparatus 8" },
      { name: "Hijab 4" },
    ],
  },
	{
    growEditionSizeTo: 1020,
    layersOrder: [
      { name: "Background" },
      { name: "Kimberly" },
      { name: "Facial Scar 3" },        
      { name: "Uniform 3" },
      { name: "Rank 4" },
      { name: "Eyebrows 3" },
      { name: "Eyes 3" },
      { name: "Nose 3" },
      { name: "Lips 3" },
      { name: "Gadgets 6" },
      { name: "Apparatus 6" },
      { name: "Hijab 3" },
    ],
  },
	{
    growEditionSizeTo: 1040,
    layersOrder: [
      { name: "Background" },
      { name: "Konala" },
      { name: "Facial Scar 10" },
      { name: "Uniform 9" },
      { name: "Rank 7" },
      { name: "Eyebrows 10" },
      { name: "Eyes 10" },
      { name: "Nose 10" },
      { name: "Lips 10" },			
      { name: "Gadgets 15" },
      { name: "Facial Features 5" },	
      { name: "Hair 10" },
    ],
  },
	{
    growEditionSizeTo: 1060,
    layersOrder: [
      { name: "Background" },
      { name: "Laila" },
      { name: "Facial Scar 4" },        
      { name: "Uniform 1" },
      { name: "Rank 2" },
      { name: "Eyebrows 4" },
      { name: "Eyes 4" },
      { name: "Nose 4" },
      { name: "Lips 4" },
      { name: "Gadgets 7" },
      { name: "Apparatus 7" },
      { name: "Hair 4" },
    ],
  },
	{
    growEditionSizeTo: 1080,
    layersOrder: [
      { name: "Background" },
      { name: "Lesedi" },
      { name: "Facial Scar 1" },         
      { name: "Uniform 3" },
      { name: "Rank 4" },
      { name: "Eyebrows 1" },
      { name: "Eyes 1" },
      { name: "Nose 1" },
      { name: "Lips 1" },
      { name: "Gadgets 1" },
      { name: "Apparatus 1" },
      { name: "Hair 1" },
    ],
  },
	{
    growEditionSizeTo: 1100,
    layersOrder: [
      { name: "Background" },
      { name: "Li Li" },
      { name: "Facial Scar 2" },        
      { name: "Uniform 4" },
      { name: "Rank 1" },
      { name: "Eyebrows 2" },
      { name: "Eyes 2" },
      { name: "Nose 2" },
      { name: "Lips 2" },
      { name: "Gadgets 3" },
      { name: "Apparatus 3" },
      { name: "Hair 2" },
    ],
  },
	{
    growEditionSizeTo: 1120,
    layersOrder: [
      { name: "Background" },
      { name: "Lilo" },
      { name: "Facial Scar 10" },        
      { name: "Uniform 12" },
      { name: "Rank 8" },
      { name: "Eyebrows 10" },
      { name: "Eyes 10" },
      { name: "Nose 10" },
      { name: "Lips 10" },			
      { name: "Gadgets 15" },
      { name: "Facial Features 5" },	
      { name: "Hair 10" },
    ],
  },
	{
    growEditionSizeTo: 1140,
    layersOrder: [
      { name: "Background" },
      { name: "Luanna" },
      { name: "Facial Scar 5" },        
      { name: "Uniform 4" },
      { name: "Rank 1" },
      { name: "Eyebrows 5" },
      { name: "Eyes 5" },
      { name: "Nose 5" },
      { name: "Lips 5" },
      { name: "Gadgets 10" },
      { name: "Apparatus 10" },
      { name: "Hijab 5" },
    ],
  },
	{
    growEditionSizeTo: 1160,
    layersOrder: [
      { name: "Background" },
      { name: "Maiele" },
      { name: "Facial Scar 10" },        
      { name: "Uniform 13" },
      { name: "Rank 8" },
      { name: "Eyebrows 10" },
      { name: "Eyes 10" },
      { name: "Nose 10" },
      { name: "Lips 10" },				
      { name: "Gadgets 15" },
      { name: "Facial Features 5" },
      { name: "Hair 10" },
    ],
  },
	{
    growEditionSizeTo: 1180,
    layersOrder: [
		{name: "Background" },
      { name: "Malana" },
      { name: "Facial Scar 5" },        
      { name: "Uniform 5" },
      { name: "Rank 4" },
      { name: "Eyebrows 5" },
      { name: "Eyes 5" },
      { name: "Nose 5" },
      { name: "Lips 5" },
      { name: "Gadgets 10" },
      { name: "Apparatus 10" },
      { name: "Hijab 5" },
    ],
  },
	{
    growEditionSizeTo: 1200,
    layersOrder: [
      { name: "Background" },
      { name: "Malo" },
      { name: "Facial Scar 10" },        
      { name: "Uniform 14" },
      { name: "Rank 8" },
      { name: "Eyebrows 10" },
      { name: "Eyes 10" },
      { name: "Nose 10" },
      { name: "Lips 10" },				
      { name: "Gadgets 15" },
      { name: "Facial Features 5" },
      { name: "Hair 10" },
    ],
  },
	{
    growEditionSizeTo: 1220,
    layersOrder: [
      { name: "Background" },
      { name: "Maluhia" },
      { name: "Facial Scar 5" },        
      { name: "Uniform 7" },
      { name: "Rank 4" },
      { name: "Eyebrows 5" },
      { name: "Eyes 5" },
      { name: "Nose 5" },
      { name: "Lips 5" },
      { name: "Gadgets 9" },
      { name: "Apparatus 9" },
      { name: "Hair 5" },
    ],
  },
	{
    growEditionSizeTo: 1240,
    layersOrder: [
      { name: "Background" },
      { name: "Mandla" },
      { name: "Facial Scar 6" },        
      { name: "Uniform 13" },
      { name: "Rank 8" },
      { name: "Eyebrows 6" },
      { name: "Eyes 6" },
      { name: "Nose 6" },
      { name: "Lips 6" },				
      { name: "Gadgets 11" },
      { name: "Facial Features 1" },
      { name: "Hair 6" },
    ],
  },
	{
    growEditionSizeTo: 1260,
    layersOrder: [
      { name: "Background" },
      { name: "Abolfazl" },
      { name: "Facial Scar 9" },        
      { name: "Uniform 8" },
      { name: "Rank 6" },
      { name: "Eyebrows 9" },
      { name: "Eyes 9" },
      { name: "Nose 9" },
      { name: "Lips 9" },			
      { name: "Gadgets 14" },
      { name: "Facial Features 4" },	
      { name: "Hair 9" },
    ],
  },
	{
    growEditionSizeTo: 1280,
    layersOrder: [
      { name: "Background" },
      { name: "Marissa" },
      { name: "Facial Scar 3" },        
      { name: "Uniform 1" },
      { name: "Rank 2" },
      { name: "Eyebrows 3" },
      { name: "Eyes 3" },
      { name: "Nose 3" },
      { name: "Lips 3" },
      { name: "Gadgets 6" },
      { name: "Apparatus 6" },
      { name: "Hijab 3" },
    ],
  },
	{
    growEditionSizeTo: 1300,
    layersOrder: [
      { name: "Background" },
      { name: "Marjani" },
      { name: "Facial Scar 1" },         
      { name: "Uniform 4" },
      { name: "Rank 1" },
      { name: "Eyebrows 1" },
      { name: "Eyes 1" },
      { name: "Nose 1" },
      { name: "Lips 1" },
      { name: "Gadgets 2" },
      { name: "Apparatus 2" },
      { name: "Hijab 1" },
    ],
  },
	{
    growEditionSizeTo: 1320,
    layersOrder: [
      { name: "Background" },
      { name: "Mason" },
      { name: "Facial Scar 8" },        
      { name: "Uniform 13" },
      { name: "Rank 8" },
      { name: "Eyebrows 8" },
      { name: "Eyes 8" },
      { name: "Nose 8" },
      { name: "Lips 8" },				
      { name: "Gadgets 13" },
      { name: "Facial Features 3" },
      { name: "Hair 8" },
    ],
  },
	{
    growEditionSizeTo: 1340,
    layersOrder: [
      { name: "Background" },
      { name: "Masoumeh" },
      { name: "Facial Scar 4" },        
      { name: "Uniform 6" },
      { name: "Rank 4" },
      { name: "Eyebrows 4" },
      { name: "Eyes 4" },
      { name: "Nose 4" },
      { name: "Lips 4" },
      { name: "Gadgets 7" },
      { name: "Apparatus 7" },
      { name: "Hair 4" },
    ],
  },
	{
    growEditionSizeTo: 1360,
    layersOrder: [
      { name: "Background" },
      { name: "Meredith" },
      { name: "Facial Scar 3" },        
      { name: "Uniform 4" },
      { name: "Rank 1" },
      { name: "Eyebrows 3" },
      { name: "Eyes 3" },
      { name: "Nose 3" },
      { name: "Lips 3" },
      { name: "Gadgets 6" },
      { name: "Apparatus 6" },
      { name: "Hijab 3" },
    ],
  },
	{
    growEditionSizeTo: 1380,
    layersOrder: [
      { name: "Background" },
      { name: "Michelle" },
      { name: "Facial Scar 3" },        
      { name: "Uniform 5" },
      { name: "Rank 4" },
      { name: "Eyebrows 3" },
      { name: "Eyes 3" },
      { name: "Nose 3" },
      { name: "Lips 3" },
      { name: "Gadgets 5" },
      { name: "Apparatus 5" },
      { name: "Hair 3" },
    ],
  },
	{
    growEditionSizeTo: 1400,
    layersOrder: [
      { name: "Background" },
      { name: "Mona" },
      { name: "Facial Scar 4" },        
      { name: "Uniform 5" },
      { name: "Rank 4" },
      { name: "Eyebrows 4" },
      { name: "Eyes 4" },
      { name: "Nose 4" },
      { name: "Lips 4" },
      { name: "Gadgets 8" },
      { name: "Apparatus 8" },
      { name: "Hijab 4" },
    ],
  },
	{
    growEditionSizeTo: 1420,
    layersOrder: [
      { name: "Background" },
      { name: "Saman" },
      { name: "Facial Scar 9" },        
      { name: "Uniform 13" },
      { name: "Rank 8" },
      { name: "Eyebrows 9" },
      { name: "Eyes 9" },
      { name: "Nose 9" },
      { name: "Lips 9" },			
      { name: "Gadgets 14" },
      { name: "Facial Features 4" },	
      { name: "Hair 9" },
    ],
  },
	{
    growEditionSizeTo: 1440,
    layersOrder: [
      { name: "Background" },
      { name: "Nahid" },
      { name: "Facial Scar 4" },        
      { name: "Uniform 3" },
      { name: "Rank 4" },
      { name: "Eyebrows 4" },
      { name: "Eyes 4" },
      { name: "Nose 4" },
      { name: "Lips 4" },
      { name: "Gadgets 7" },
      { name: "Apparatus 7" },
      { name: "Hair 4" },
    ],
  },
	{
    growEditionSizeTo: 1460,
    layersOrder: [
      { name: "Background" },
      { name: "Natalie" },
      { name: "Facial Scar 3" },        
      { name: "Uniform 5" },
      { name: "Rank 4" },
      { name: "Eyebrows 3" },
      { name: "Eyes 3" },
      { name: "Nose 3" },
      { name: "Lips 3" },
      { name: "Gadgets 6" },
      { name: "Apparatus 6" },
      { name: "Hijab 3" },
    ],
  },
	{
    growEditionSizeTo: 1480,
    layersOrder: [
      { name: "Background" },
      { name: "Nazanin" },
      { name: "Facial Scar 4" },        
      { name: "Uniform 4" },
      { name: "Rank 1" },
      { name: "Eyebrows 4" },
      { name: "Eyes 4" },
      { name: "Nose 4" },
      { name: "Lips 4" },
      { name: "Gadgets 8" },
      { name: "Apparatus 7" },
      { name: "Hijab 4" },
    ],
  },
	{
    growEditionSizeTo: 1500,
    layersOrder: [
      { name: "Background" },
      { name: "Nazri" },
      { name: "Facial Scar 7" },        
      { name: "Uniform 8" },
      { name: "Rank 6" },
      { name: "Eyebrows 7" },
      { name: "Eyes 7" },
      { name: "Nose 7" },
      { name: "Lips 7" },			
      { name: "Gadgets 12" },
      { name: "Facial Features 2" },	
      { name: "Hair 7" },
    ],
  },
	{
    growEditionSizeTo: 1520,
    layersOrder: [
      { name: "Background" },
      { name: "Nemy" },
      { name: "Facial Scar 1" },         
      { name: "Uniform 5" },
      { name: "Rank 4" },
      { name: "Eyebrows 1" },
      { name: "Eyes 1" },
      { name: "Nose 1" },
      { name: "Lips 1" },
      { name: "Gadgets 1" },
      { name: "Apparatus 1" },
      { name: "Hair 1" },
    ],
  },
	{
    growEditionSizeTo: 1540,
    layersOrder: [
      { name: "Background" },
      { name: "Ngozi" },
      { name: "Facial Scar 1" },         
      { name: "Uniform 1" },
      { name: "Rank 2" },
      { name: "Eyebrows 1" },
      { name: "Eyes 1" },
      { name: "Nose 1" },
      { name: "Lips 1" },
      { name: "Gadgets 1" },
      { name: "Apparatus 1" },
      { name: "Hair 1" },
    ],
  },
	{
    growEditionSizeTo: 1560,
    layersOrder: [
      { name: "Background" },
      { name: "Nohealani" },
      { name: "Facial Scar 5" },        
      { name: "Uniform 3" },
      { name: "Rank 4" },
      { name: "Eyebrows 5" },
      { name: "Eyes 5" },
      { name: "Nose 5" },
      { name: "Lips 5" },
      { name: "Gadgets 9" },
      { name: "Apparatus 9" },
      { name: "Hair 5" },
    ],
  },
	{
    growEditionSizeTo: 1580,
    layersOrder: [
      { name: "Background" },
      { name: "Olaga" },
      { name: "Facial Scar 5" },        
      { name: "Uniform 6" },
      { name: "Rank 4" },
      { name: "Eyebrows 5" },
      { name: "Eyes 5" },
      { name: "Nose 5" },
      { name: "Lips 5" },
      { name: "Gadgets 9" },
      { name: "Apparatus 9" },
      { name: "Hair 5" },
    ],
  },
	{
    growEditionSizeTo: 1600,
    layersOrder: [
      { name: "Background" },
      { name: "OliOli" },
      { name: "Facial Scar 5" },        
      { name: "Uniform 6" },
      { name: "Rank 4" },
      { name: "Eyebrows 5" },
      { name: "Eyes 5" },
      { name: "Nose 5" },
      { name: "Lips 5" },
      { name: "Gadgets 10" },
      { name: "Apparatus 10" },
      { name: "Hijab 5" },
    ],
  },
	{
    growEditionSizeTo: 1620,
    layersOrder: [
      { name: "Background" },
      { name: "Onosa'i" },
      { name: "Facial Scar 5" },
      { name: "Uniform 2" },
      { name: "Rank 3" },
      { name: "Eyebrows 5" },
      { name: "Eyes 5" },
      { name: "Nose 5" },
      { name: "Lips 5" },
      { name: "Gadgets 9" },
      { name: "Apparatus 9" },
      { name: "Hair 5" },
    ],
  },
	{
    growEditionSizeTo: 1640,
    layersOrder: [
      { name: "Background" },
      { name: "Palesa" },
      { name: "Facial Scar 1" },         
      { name: "Uniform 4" },
      { name: "Rank 1" },
      { name: "Eyebrows 1" },
      { name: "Eyes 1" },
      { name: "Nose 1" },
      { name: "Lips 1" },
      { name: "Gadgets 1" },
      { name: "Apparatus 1" },
      { name: "Hair 1" },
    ],
  },
	{
    growEditionSizeTo: 1680,
    layersOrder: [
      { name: "Background" },
      { name: "Penina" },
      { name: "Facial Scar 5" },        
      { name: "Uniform 4" },
      { name: "Rank 1" },
      { name: "Eyebrows 5" },
      { name: "Eyes 5" },
      { name: "Nose 5" },
      { name: "Lips 5" },
      { name: "Gadgets 9" },
      { name: "Apparatus 9" },
      { name: "Hair 5" },
    ],
  },
	{
    growEditionSizeTo: 1700,
    layersOrder: [
      { name: "Background" },
      { name: "Salana" },
      { name: "Facial Scar 1" },         
      { name: "Uniform 6" },
      { name: "Rank 4" },
      { name: "Eyebrows 1" },
      { name: "Eyes 1" },
      { name: "Nose 1" },
      { name: "Lips 1" },
      { name: "Gadgets 1" },
      { name: "Apparatus 1" },
      { name: "Hair 1" },
    ],
  },
	{
    growEditionSizeTo: 1720,
    layersOrder: [
      { name: "Background" },
      { name: "Samantha" },
      { name: "Facial Scar 3" },        
      { name: "Uniform 6" },
      { name: "Rank 4" },
      { name: "Eyebrows 3" },
      { name: "Eyes 3" },
      { name: "Nose 3" },
      { name: "Lips 3" },
      { name: "Gadgets 6" },
      { name: "Apparatus 6" },
      { name: "Hijab 3" },
    ],
  },
	{
    growEditionSizeTo: 1740,
    layersOrder: [
      { name: "Background" },
      { name: "Samira" },
      { name: "Facial Scar 4" },        
      { name: "Uniform 7" },
      { name: "Rank 4" },
      { name: "Eyebrows 4" },
      { name: "Eyes 4" },
      { name: "Nose 4" },
      { name: "Lips 4" },
      { name: "Gadgets 8" },
      { name: "Apparatus 8" },
      { name: "Hijab 4" },
    ],
  },
	{
    growEditionSizeTo: 1760,
    layersOrder: [
      { name: "Background" },
      { name: "Samiya" },
      { name: "Facial Scar 1" },         
      { name: "Uniform 3" },
      { name: "Rank 4" },
      { name: "Eyebrows 1" },
      { name: "Eyes 1" },
      { name: "Nose 1" },
      { name: "Lips 1" },
      { name: "Gadgets 2" },
      { name: "Apparatus 2" },
      { name: "Hijab 1" },
    ],
  },
	{
    growEditionSizeTo: 1780,
    layersOrder: [
      { name: "Background" },
      { name: "Serika" },
      { name: "Facial Scar 2" },        
      { name: "Uniform 3" },
      { name: "Rank 4" },
      { name: "Eyebrows 2" },
      { name: "Eyes 2" },
      { name: "Nose 2" },
      { name: "Lips 2" },
      { name: "Gadgets 3" },
      { name: "Apparatus 3" },
      { name: "Hair 2" },
    ],
  },
	{
    growEditionSizeTo: 1800,
    layersOrder: [
      { name: "Background" },
      { name: "Sethe" },
      { name: "Facial Scar 1" },         
      { name: "Uniform 7" },
      { name: "Rank 4" },
      { name: "Eyebrows 1" },
      { name: "Eyes 1" },
      { name: "Nose 1" },
      { name: "Lips 1" },
      { name: "Gadgets 1" },
      { name: "Apparatus 1" },
      { name: "Hair 1" },
    ],
  },
	{
    growEditionSizeTo: 1820,
    layersOrder: [
      { name: "Background" },
      { name: "Shahrazad" },
      { name: "Facial Scar 4" },        
      { name: "Uniform 6" },
      { name: "Rank 4" },
      { name: "Eyebrows 4" },
      { name: "Eyes 4" },
      { name: "Nose 4" },
      { name: "Lips 4" },
      { name: "Gadgets 8" },
      { name: "Apparatus 8" },
      { name: "Hijab 4" },
    ],
  },
	{
    growEditionSizeTo: 1840,
    layersOrder: [
      { name: "Background" },
      { name: "Shaurya" },
      { name: "Facial Scar 7" },        
      { name: "Uniform 14" },
      { name: "Rank 8" },
      { name: "Eyebrows 7" },
      { name: "Eyes 7" },
      { name: "Nose 7" },
      { name: "Lips 7" },			
      { name: "Gadgets 12" },
      { name: "Facial Features 2" },	
      { name: "Hair 7" },
    ],
  },
	{
    growEditionSizeTo: 1860,
    layersOrder: [
      { name: "Background" },
      { name: "Sielu" },
      { name: "Facial Scar 10" },        
      { name: "Uniform 8" },
      { name: "Rank 6" },
      { name: "Eyebrows 10" },
      { name: "Eyes 10" },
      { name: "Nose 10" },
      { name: "Lips 10" },			
      { name: "Gadgets 15" },
      { name: "Facial Features 5" },	
      { name: "Hair 10" },
    ],
  },
	{
    growEditionSizeTo: 1880,
    layersOrder: [
      { name: "Background" },
      { name: "Sora" },
      { name: "Facial Scar 3" },        
      { name: "Uniform 2" },
      { name: "Rank 3" },
      { name: "Eyebrows 3" },
      { name: "Eyes 3" },
      { name: "Nose 3" },
      { name: "Lips 3" },
      { name: "Gadgets 6" },
      { name: "Apparatus 6" },
      { name: "Hijab 3" },
    ],
  },
	{
    growEditionSizeTo: 1900,
    layersOrder: [
      { name: "Background" },
      { name: "Soraya" },
      { name: "Facial Scar 4" },        
      { name: "Uniform 4" },
      { name: "Rank 1" },
      { name: "Eyebrows 4" },
      { name: "Eyes 4" },
      { name: "Nose 4" },
      { name: "Lips 4" },
      { name: "Gadgets 7" },
      { name: "Apparatus 7" },
      { name: "Hair 4" },
    ],
  },
	{
    growEditionSizeTo: 1920,
    layersOrder: [
      { name: "Background" },
      { name: "Sudarshini" },
      { name: "Facial Scar 2" },        
      { name: "Uniform 7" },
      { name: "Rank 4" },
      { name: "Eyebrows 2" },
      { name: "Eyes 2" },
      { name: "Nose 2" },
      { name: "Lips 2" },
      { name: "Gadgets 4" },
      { name: "Apparatus 4" },
      { name: "Hijab 2" },
    ],
  },
	{
    growEditionSizeTo: 1940,
    layersOrder: [
      { name: "Background" },
      { name: "Pedram" },
      { name: "Facial Scar 9" },        
      { name: "Uniform 10" },
      { name: "Rank 8" },
      { name: "Eyebrows 9" },
      { name: "Eyes 9" },
      { name: "Nose 9" },
      { name: "Lips 9" },			
      { name: "Gadgets 14" },
      { name: "Facial Features 4" },	
      { name: "Hair 9" },
    ],
  },
	{
    growEditionSizeTo: 1960,
    layersOrder: [
      { name: "Background" },
      { name: "Sumiko" },
      { name: "Facial Scar 2" },        
      { name: "Uniform 6" },
      { name: "Rank 4" },
      { name: "Eyebrows 2" },
      { name: "Eyes 2" },
      { name: "Nose 2" },
      { name: "Lips 2" },
      { name: "Gadgets 3" },
      { name: "Apparatus 3" },
      { name: "Hair 2" },
    ],
  },
	{
    growEditionSizeTo: 1980,
    layersOrder: [
      { name: "Background" },
      { name: "Suravi" },
      { name: "Facial Scar 2" },        
      { name: "Uniform 6" },
      { name: "Rank 4" },
      { name: "Eyebrows 2" },
      { name: "Eyes 2" },
      { name: "Nose 2" },
      { name: "Lips 2" },
      { name: "Gadgets 4" },
      { name: "Apparatus 4" },
      { name: "Hijab 2" },
    ],
  },
	{
    growEditionSizeTo: 2000,
    layersOrder: [
      { name: "Background" },
      { name: "Trang" },
      { name: "Facial Scar 2" },        
      { name: "Uniform 5" },
      { name: "Rank 4" },
      { name: "Eyebrows 2" },
      { name: "Eyes 2" },
      { name: "Nose 2" },
      { name: "Lips 2" },
      { name: "Gadgets 3" },
      { name: "Apparatus 3" },
      { name: "Hair 2" },
    ],
  },
	{
    growEditionSizeTo: 2020,
    layersOrder: [
      { name: "Background" },
      { name: "Troy" },
      { name: "Facial Scar 8" },        
      { name: "Uniform 11" },
      { name: "Rank 5" },
      { name: "Eyebrows 8" },
      { name: "Eyes 8" },
      { name: "Nose 8" },
      { name: "Lips 8" },			
      { name: "Gadgets 13" },
      { name: "Facial Features 3" },	
      { name: "Hair 8" },
    ],
  },
	{
    growEditionSizeTo: 2040,
    layersOrder: [
      { name: "Background" },
      { name: "Will" },
      { name: "Facial Scar 8" },        
      { name: "Uniform 8" },
      { name: "Rank 6" },
      { name: "Eyebrows 8" },
      { name: "Eyes 8" },
      { name: "Nose 8" },
      { name: "Lips 8" },				
      { name: "Gadgets 13" },
      { name: "Facial Features 3" },
      { name: "Hair 8" },
    ],
  },
	{
    growEditionSizeTo: 2060,
    layersOrder: [
      { name: "Background" },
      { name: "Hafez" },
      { name: "Facial Scar 9" },        
      { name: "Uniform 14" },
      { name: "Rank 8" },
      { name: "Eyebrows 9" },
      { name: "Eyes 9" },
      { name: "Nose 9" },
      { name: "Lips 9" },			
      { name: "Gadgets 14" },
      { name: "Facial Features 4" },	
      { name: "Hair 9" },
    ],
  },
	{
    growEditionSizeTo: 2080,
    layersOrder: [
      { name: "Background" },
      { name: "Yasmin" },
      { name: "Facial Scar 4" },        
      { name: "Uniform 3" },
      { name: "Rank 4" },
      { name: "Eyebrows 4" },
      { name: "Eyes 4" },
      { name: "Nose 4" },
      { name: "Lips 4" },
      { name: "Gadgets 8" },
      { name: "Apparatus 8" },
      { name: "Hijab 4" },
    ],
  },
	{
    growEditionSizeTo: 2100,
    layersOrder: [
      { name: "Background" },
      { name: "Zarin" },
      { name: "Facial Scar 4" },        
      { name: "Uniform 7" },
      { name: "Rank 4" },
      { name: "Eyebrows 4" },
      { name: "Eyes 4" },
      { name: "Nose 4" },
      { name: "Lips 4" },
      { name: "Gadgets 7" },
      { name: "Apparatus 7" },
      { name: "Hair 4" },
    ],
  },
	{
    growEditionSizeTo: 2120,
    layersOrder: [
      { name: "Background" },
      { name: "Zizi" },
      { name: "Facial Scar 1" },         
      { name: "Uniform 5" },
      { name: "Rank 4" },
      { name: "Eyebrows 1" },
      { name: "Eyes 1" },
      { name: "Nose 1" },
      { name: "Lips 1" },
      { name: "Gadgets 2" },
      { name: "Apparatus 2" },
      { name: "Hijab 1" },
    ],
  },
];

const shuffleLayerConfigurations = true;

const debugLogs = false;

const format = {
  width: 3000,
  height: 3000,
  smoothing: false,
};

const extraMetadata = {
  external_url: "https://unknownfederation.xyz", // Replace with your website or remove this line if you do not have one.
  creator: "Ultra Silvafine",
};

// NFTPort Info

// ** REQUIRED **
const AUTH = process.env.NFTPORT_API_KEY; // Set this in the .env file to prevent exposing your API key when pushing to Github
const LIMIT = 10; // Your API key rate limit
const CHAIN = 'goerli'; // only goerli, polygon, or ethereum

// REQUIRED CONTRACT DETAILS THAT CANNOT BE UPDATED LATER!
const CONTRACT_NAME = 'Unknown Federation';
const CONTRACT_SYMBOL = 'UKF';
const METADATA_UPDATABLE = true; // set to false if you don't want to allow metadata updates after minting
const OWNER_ADDRESS = '0x4F9206707B79B3caE72E6D5465885888000C1075';
const TREASURY_ADDRESS = '0x4F9206707B79B3caE72E6D5465885888000C1075';
const MAX_SUPPLY = 10000; // The maximum number of NFTs that can be minted. CANNOT BE UPDATED!
const MINT_PRICE = 0.001; // Minting price per NFT. Goerli = ETH, Ethereum = ETH, Polygon = MATIC. CANNOT BE UPDATED!
const TOKENS_PER_MINT = 10; // maximum number of NFTs a user can mint in a single transaction. CANNOT BE UPDATED!

// REQUIRED CONTRACT DETAILS THAT CAN BE UPDATED LATER.
const PUBLIC_MINT_START_DATE = "2022-11-20T11:30:48+00:00"; // This is required. Eg: 2022-02-08T11:30:48+00:00

// OPTIONAL CONTRACT DETAILS THAT CAN BE UPDATED LATER.
const PRESALE_MINT_START_DATE = "2022-10-18T11:30:48+00:00"; // Optional. Eg: 2022-02-08T11:30:48+00:00
const ROYALTY_SHARE = 250; // 000Percentage of the token price that goes to the royalty address. 100 bps = 1%
const ROYALTY_ADDRESS = "0x4F9206707B79B3caE72E6D5465885888000C1075"; // Address that will receive the royalty
const BASE_URI = null; // only update if you want to manually set the base uri
const PREREVEAL_TOKEN_URI = null; // only update if you want to manually set the prereveal token uri
const PRESALE_WHITELISTED_ADDRESSES = []; // only update if you want to manually set the whitelisted addresses

// ** OPTIONAL **
let CONTRACT_ADDRESS = "YOUR CONTRACT ADDRESS"; // If you want to manually include it

// Generic Metadata is optional if you want to reveal your NFTs
const GENERIC = true; // Set to true if you want to upload generic metas and reveal the real NFTs in the future
const GENERIC_TITLE = CONTRACT_NAME; // Replace with what you want the generic titles to say if you want it to be different from the contract name.
const GENERIC_DESCRIPTION = "Which crew member will you get?"; // Replace with what you want the generic descriptions to say.
const GENERIC_IMAGE = "https://ipfs.io/ipfs/bafybeihypm2bipgejs23awi4g7d25oas4rghmeksjodmhcp4azbaxo52ym"; // Replace with your generic image that will display for all NFTs pre-reveal.

// Automatically set contract address if deployed using the deployContract.js script
try {
  const rawContractData = fs.readFileSync(
    `${basePath}/build/contract/_contract.json`
  );
  const contractData = JSON.parse(rawContractData);
  if (contractData.response === "OK") {
    CONTRACT_ADDRESS = contractData.contract_address;
  }
} catch (error) {
  // Do nothing, falling back to manual contract address
}
// END NFTPort Info

const solanaMetadata = {
  symbol: "UKF",
  seller_fee_basis_points: 250, // Define how much % you want from secondary market sales 1000 = 10%
  external_url: "https://unknownfederation.xyz",
  creators: [
    {
      address: "7fXNuer5sbZtaTEPhtJ5g5gNtuyRoKkvxdjEjEnPN4mC",
      share: 100,
    },
  ],
};

const gif = {
  export: false,
  repeat: 0,
  quality: 100,
  delay: 500,
};

const text = {
  only: false,
  color: "#ffffff",
  size: 20,
  xGap: 40,
  yGap: 40,
  align: "left",
  baseline: "top",
  weight: "regular",
  family: "Courier",
  spacer: " => ",
};

const pixelFormat = {
  ratio: 2 / 128,
};

const background = {
  generate: true,

  brightness: "80%",
  static: false,
  default: "#000000",
};

const rarityDelimiter = "#";

const uniqueDnaTorrance = 10000;

const preview = {
  thumbPerRow: 5,
  thumbWidth: 50,
  imageRatio: format.height / format.width,
  imageName: "preview.png",
};

const preview_gif = {
  numberOfImages: 5,
  order: "ASC", // ASC, DESC, MIXED
  repeat: 0,
  quality: 100,
  delay: 500,
  imageName: "preview.gif",
};

module.exports = {
  format,
  baseUri,
  description,
  background,
  uniqueDnaTorrance,
  layerConfigurations,
  rarityDelimiter,
  preview,
  shuffleLayerConfigurations,
  debugLogs,
  extraMetadata,
  pixelFormat,
  text,
  namePrefix,
  network,
  solanaMetadata,
  gif,
  preview_gif,
  AUTH,
  LIMIT,
  CONTRACT_ADDRESS,
  OWNER_ADDRESS,
  TREASURY_ADDRESS,
  CHAIN,
  GENERIC,
  GENERIC_TITLE,
  GENERIC_DESCRIPTION,
  GENERIC_IMAGE,
  CONTRACT_NAME,
  CONTRACT_SYMBOL,
  METADATA_UPDATABLE,
  ROYALTY_SHARE,
  ROYALTY_ADDRESS,
  MAX_SUPPLY,
  MINT_PRICE,
  TOKENS_PER_MINT,
  PRESALE_MINT_START_DATE,
  PUBLIC_MINT_START_DATE,
  BASE_URI,
  PREREVEAL_TOKEN_URI,
  PRESALE_WHITELISTED_ADDRESSES
};
