const contractAddress = "0xA96A377A55Fb768E2A1D96E5f0a266B71acc14D8"; // Replace with your own contract address
const chain = 'ethereum'; // goerli, polygon, or ethereum

const welcome_h1 = "Welcome to Unknown Federation NFT Project!!";
const welcome_h2 = "Connect to MetaMask to Get Started";
const welcome_p = 'Unknown Federation NFT Project is a NFT collection of cadets and officers that is inspired by famous sci-fi tv series like Star Trek and The Orville. The owner of this NFT collection will get lifetime access of a FREE mutiple choice, multiple ending interactive novel that will be develop if we manage to sold out this collection. The characters that you own will be the star of that novel. Owners will also enjoy free Print on Demand products from Redbubble (Terms and conditions applies) and giveaways such as Airdrop NFTs that will be conducted in our Discord server.';
const h1_presale_coming_soon = "NFT Drop Coming Soon!!";
const h1_presale_mint = "Pre-Sale Minting Open!!";
const h1_public_mint = "Public Minting Open!!";
const h2_presale_coming_soon = "Pre-Sale Minting Countdown";
const h2_presale_mint = "Public Minting Countdown";
const p_presale_coming_soon = "We are working hard to launch the NFT Collection. Stay tuned for updates!";
const p_presale_mint_not_whitelisted = "You are not whitelisted for the pre-sale.. 😢";
const p_presale_mint_whitelisted = "You're on the whitelist for the pre-sale! 🎉";
const p_presale_mint_already_minted = "You've already claimed your whitelist mint. Thank you! 🎉";
const p_public_mint = "No whitelist needed. Public minting is now open! 🎉";
const button_presale_coming_soon = "Get on the Whitelist";
const button_presale_mint_whitelisted = "Mint Your Special NFT";
const button_presale_mint_not_whitelisted = "Get on the Whitelist";
const button_presale_already_minted = "Join The Community";
const button_public_mint = "Mint Your NFT";
const mint_failed = "Minting failed. 😢 Please try again.";
